name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Fetch submodules if any exist
          fetch-depth: 0

      - name: Setup Hugo Environment
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.134.3" # Matches the version in original template
          extended: true

      - name: Build Hugo Site
        run: hugo --minify --baseURL "https://dung23423.github.io/TrieuXuanDung_MyBlog_AWS/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
